# Deploys  django polls application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-polls
spec:
  selector:
    matchLabels:
      app: django-polls
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django-polls
    spec:
      containers:
      - image: "django:1.0"
        name: django-polls
        env:
        - name: DEV
          value: "1"
        resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "0.5"
        imagePullPolicy: Never # only for minikube builds where #eval(minikube docker-env) is used
---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 8000
  selector:
   app: django-polls
