apiVersion: v1
data:
  username: cG9zdGdyZXMK
  password: cG9zdGdyZXMK
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth

---
apiVersion: v1
data:
  username: c3VwZXJ1c2VyCg==
  password: c3VwZXJ1c2VyCg==
kind: Secret
metadata:
  name: superuser-secret
type: kubernetes.io/basic-auth

---
# cluster bu controler
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-example-initdb
spec:
  instances: 3
  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
  storage:
    size: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
   - port: 5432
  selector:
   app: postgres