apiVersion: v1
data:
  username: c3VwZXJ1c2VyCg==
  password: c3VwZXJ1c2VyCg==
kind: Secret
metadata:
  name: superuser-secret
type: kubernetes.io/basic-auth

---
# cluster bu controler
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: postgres-db
  labels:
    app: postgres
spec:
  instances: 2
  superuserSecret:
    name: superuser-secret

  storage:
    size: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-host
  labels:
    app: postgres
spec:
  ports:
   - port: 5432
  selector:
   role: primary