apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgresql-operator-system
spec:
  selector:
    matchLabels:
      postgresql: postgresql-operator-system
  podMetricsEndpoints:
  - port: metrics